version: "3.8"
services:
  database:
    image: postgres
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - '6000:6000'
    command: -p 6000
volumes:
  database:
    driver: local